services:
  postgres:
    image: postgres:17.5
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./sql-data:/var/lib/postgresql/data
    user: "503:20"

  mongodb:
    image: mongodb/mongodb-atlas-local:8.0
    container_name: mongo-atlas
    privileged: true
    restart: always
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=ardan
      - MONGODB_INITDB_ROOT_PASSWORD=ardan
    ports:
      - 27017-27019:27017-27019
    volumes:
      - ./mongo:/data
      - ./mongo/db:/data/db
      - ./mongo/configdb:/data/configdb
    user: "503:20"

  openwebui:
    image: ghcr.io/open-webui/open-webui:v0.6.18
    container_name: openwebui
    restart: always
    environment:
      - WEBUI_AUTH=false
      - GLOBAL_LOG_LEVEL="DEBUG"
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 3000:8080
    volumes:
      - ./openwebui:/app/backend/data

  docling:
    image: quay.io/docling-project/docling-serve
    container_name: docling
    restart: always
    environment:
      - DOCLING_SERVE_ENABLE_UI=1
      - DOCLING_SERVE_SCRATCH_PATH=/scratch
    ports:
      - 5001:5001
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./docling:/scratch

volumes:
  postgres: {}
  mongodb: {}
  openwebui: {}
  docling: {}
