services:
  postgres:
    image: postgres:17.5
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=[REDACTED:password]

  mongodb:
    image: mongodb/mongodb-atlas-local:8.0
    container_name: mongo-atlas
    privileged: true
    restart: always
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=ardan
      - MONGODB_INITDB_ROOT_PASSWORD=ardan
      - MONGODB_REPLICA_SET_NAME=rs0
    ports:
      - 27017-27019:27017-27019

  openwebui:
    image: ghcr.io/open-webui/open-webui:v0.6.18
    container_name: openwebui
    restart: always
    environment:
      - WEBUI_AUTH=false
      - GLOBAL_LOG_LEVEL="DEBUG"
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 3000:8080

  docling:
    image: quay.io/docling-project/docling-serve
    container_name: docling
    restart: always
    environment:
      - DOCLING_SERVE_ENABLE_UI=1
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 5001:5001

volumes:
  postgres: {}
  mongodb: {}
  openwebui: {}
  docling: {}
