services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:v0.6.18
    container_name: openwebui
    restart: always
    environment:
      - WEBUI_AUTH=false
      - GLOBAL_LOG_LEVEL="DEBUG"
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 3000:8080
    volumes:
      - ./openwebui:/app/backend/data

volumes:
  openwebui:
    external: true
    name: openwebui
