services:
  docling:
    image: quay.io/docling-project/docling-serve
    container_name: docling
    restart: always
    environment:
      - DOCLING_SERVE_ENABLE_UI=1
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 5001:5001
